var TAGSFILE,TAGS,dbobj,alarm=!1,maxpage,autorefresh=!1,curpage=0,pages=1,pubnub,total,startrow,endrow,count=0,count1=0,divn,states=[],dynDiv,h=document.createElement("H2"),tx=document.createTextNode("Monitored item list: "+channelName);h.appendChild(tx);document.body.appendChild(h);var para=document.createElement("p"),node=document.createTextNode(" ");para.id="time";para.style.fontSize="120%";para.style.color="blue";para.appendChild(node);document.body.appendChild(para);
var d=new Date+"",dt=d.substring(0,d.search("GMT"));document.getElementById("time").innerHTML=dt+"Local Time";var chkDiv=document.createElement("p"),checkbox=document.createElement("input");checkbox.id="cb";checkbox.setAttribute("type","checkbox");checkbox.checked=!1;chkDiv.appendChild(checkbox);checkbox.setAttribute("onclick","checkFunction()");var node1=document.createTextNode("Display Alarms only");chkDiv.id="chkbox";chkDiv.style.fontSize="100%";chkDiv.style.color="red";chkDiv.appendChild(node1);
document.body.appendChild(chkDiv);var autocheck=document.createElement("input");autocheck.id="ac";autocheck.setAttribute("type","checkbox");autocheck.checked=!1;chkDiv.appendChild(autocheck);autocheck.setAttribute("onclick","autoFunction()");var node2=document.createTextNode("Auto Refresh every 5 seconds");chkDiv.appendChild(node2);document.body.appendChild(chkDiv);var btn=document.createElement("BUTTON"),t=document.createTextNode("REFRESH");btn.id="btn";btn.appendChild(t);btn.onclick=function(){refresh(0)};
document.body.appendChild(btn);tableCreate();dynDiv=document.createElement("p");dynDiv.id="header";dynDiv.style.margin="0em";dynDiv.style.width="800px";dynDiv.style.fontWeight="bold";dynDiv.style.fontFamily="Arial, Helvetica, sans-serif";dynDiv.innerHTML="Sno|Tag Name |Definition   |Value|Unit  |Limit  |State";document.body.appendChild(dynDiv);
for(var i=1;i<maxpage+1;i++)dynDiv=document.createElement("p"),dynDiv.id="demo"+i,dynDiv.style.margin="0em",dynDiv.style.width="800px",dynDiv.style.fontWeight="bold",dynDiv.style.fontFamily="Arial, Helvetica, sans-serif",dynDiv.innerHTML="",document.body.appendChild(dynDiv);var btn1=document.createElement("BUTTON"),t1=document.createTextNode("<PREV");btn1.id="btn1";btn1.appendChild(t1);btn1.onclick=function(){prev()};document.body.appendChild(btn1);var btnt=document.createElement("INPUT");
btnt.id="btnt";document.body.appendChild(btnt);document.getElementById("btnt").disabled=!0;document.getElementById("btnt").setAttribute("value"," Page # of #");var btn2=document.createElement("BUTTON"),t2=document.createTextNode("NEXT>");btn2.id="btn2";btn2.appendChild(t2);btn2.onclick=function(){next()};document.body.appendChild(btn2);curpage==pages-1?document.getElementById("btn2").disabled=!0:document.getElementById("btn2").disabled=!1;function prev(){0<curpage&&(curpage--,refresh(0))}
function next(){curpage<pages-1&&(curpage++,refresh(0))}function checkFunction(){alarm=1==document.getElementById("cb").checked?!0:!1;curpage=0;refresh(0)}function autoFunction(){1==document.getElementById("ac").checked?(autorefresh=!0,document.getElementById("btn").disabled=!0):(autorefresh=!1,document.getElementById("btn").disabled=!1);console.log("autorefresh=",autorefresh)}
function tableCreate(){var a=document.body,b=document.createElement("table");b.style.border="1px solid black";for(var c=0;1>c;c++){var g=b.insertRow();g.style.border="1px solid black";for(var e=0;10>e;e++){var f=g.insertCell();f.style.border="1px solid black";f.appendChild(document.createTextNode("State "+e));f.style.backgroundColor=color[e]}}a.appendChild(b)}
function refresh(a){if(1!=a||autorefresh)pubnub.publish({channel:"command_channel",message:{msg:"SCAN "+TAGSFILE}}),console.log("refresh called")}pubnub=new PubNub({publishKey:publish_key,subscribeKey:subscribe_key});function publishMessage(){pubnub.publish({channel:"command_channel",message:{msg:"GETTAGS "+TAGSFILE}},function(a,b){})}
pubnub.addListener({message:function(a){var b=a.channel;a=a.message;if(!b.startsWith("TABLE"))if(a=a.split("^"),"response"==b&&"GETTAGS"==a[0].trim()){dbobj=JSON.parse('{"TAGDB":'+a[1]+"}");TAGS='{"TAGS":"ARSTATUS~';for(b=0;b<dbobj.TAGDB.length;b++)TAGS+=dbobj.TAGDB[b].name+"~";TAGS+='"}';curpage=0;refresh(0)}else if("response"==b&&"SCAN"==a[0].trim()){b=JSON.parse(a[1]).value;d=new Date+"";dt=d.substring(0,d.search("GMT"));document.getElementById("time").innerHTML=dt+"Local Time";states=b.split("~");
total=states.length;""==states[total-1]&&total--;total--;if(1==alarm){a=0;for(b=1;b<total;b++){var c;c=states[b].split(",");0<parseInt(c[1])&&a++}pages=Math.floor(a/maxpage)+1}else pages=Math.floor(total/maxpage)+1;console.log("pages=",pages);startrow=curpage*maxpage;endrow=(pages+1)*maxpage;document.getElementById("btnt").setAttribute("value"," Page "+(curpage+1)+" of "+pages);0==curpage?document.getElementById("btn1").disabled=!0:document.getElementById("btn1").disabled=!1;curpage==pages-1?document.getElementById("btn2").disabled=
!0:document.getElementById("btn2").disabled=!1;count1=0;for(count=startrow;count<endrow;count++)if(b=states[count+1].split(","),a=parseInt(b[1]),!alarm||0!=a){if(count>total-1||count1>maxpage-1)break;count1++;divn="demo"+count1;c=count1+curpage*maxpage+"";10>count1?c="00"+c:100>count1&&(c="0"+c);document.getElementById(divn).innerHTML=c+"| "+dbobj.TAGDB[count].name+"| "+dbobj.TAGDB[count].def+"| "+b[0]+"| "+dbobj.TAGDB[count].unit+"| "+dbobj.TAGDB[count].conditions[a].cond+dbobj.TAGDB[count].conditions[a].lim+
"| "+dbobj.TAGDB[count].conditions[a].label;document.getElementById(divn).style.fontWeight="bold";document.getElementById(divn).style.backgroundColor=color[a];document.getElementById(divn).style.color=fcolor[a]}if(count1<maxpage)for(count=count1+1;count<maxpage+1;count++)divn="demo"+count,document.getElementById(divn).innerHTML=""}},presence:function(a){},status:function(a){switch(a.category){case "PNNetworkDownCategory":console.log("Connection error: PNNetworkDownCategory - connection is not available or this is not able to reach the PubNub Data Stream Network.");
break;case "PNNetworkIssuesCategory":console.log("Connection error: PNNetworkIssuesCategory - A subscribe event experienced an exception when running. The SDK is not being to able reach the PubNub Data Stream Network because the machine or device are not connected to Internet or this has been lost, your ISP (Internet Service Provider) is having to troubles or perhaps or the SDK is behind of a proxy.");break;case "PNReconnectedCategory":console.log("Connection error : PNReconnectedCategory - reconnected ");
break;case "PNConnectedCategory":console.log("PNConnected");publishMessage();setInterval(function(){refresh(1)},5E3);break;case "PNAccessDeniedCategory":console.log("Connection error : PNAccessDeniedCategory - PAM permission denied ");break;case "PNMalformedResponseCategory":console.log("Connection error : PNMalformedResponseCategory - JSON parsing crashed.");break;case "PNBadRequestCategory":console.log("Connection error : PNBadRequestCategory: //The server responded with bad response because the request is malformed.");
break;case "PNDecryptionErrorCategory":console.log("Connection error : PNDecryptionErrorCategory: //If using decryption strategies and the decryption fails.");break;case "PNTimeoutCategory":console.log("Connection error : PNTimeoutCategory: Failure to establish connection due to timeout.");break;case "PNRequestMessageCountExceedCategory":console.log("Connection error : PNRequestMessageCountExceedCategory: requestMessageCountThreshold is set and the number of messages arrived from (PubNub in memory cache messages) are greater than this.");
break;case "PNUnknownCategory":console.log("Connection error : PNUnknownCategory - non 200 HTTP response code from the server.")}}});console.log("Subscribing..");pubnub.subscribe({channels:[channelName,"response"]});
